name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
          BUILD_SCRIPT: yarn global add vuepress && yarn docs:build
          CNAME: awssat.com
