name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          yarn global add vuepress 
          yarn install
          yarn docs:build
          cp ./CNAME ./docs/CNAME

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: awssat/awssat.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./docs